import { createRecordBank } from '../src/characters/records.js';
import { prepareProfileItems, createProfile } from './fixtures/legacy-profiles.mjs';
import assert from 'node:assert/strict';
import http from 'node:http';
import { readFile, mkdir } from 'node:fs/promises';
import path from 'node:path';
import { createRequire } from 'node:module';
import { createHash } from 'node:crypto';
const require=createRequire(import.meta.url);
const { chromium }=require('playwright');
const root=path.resolve(import.meta.dirname,'..');
const prefix='/scripts/extensions/third-party/scene-reader/';
const wadeSource='Name: Wade\nRole: Businessman.\nHe controls his son.\nHe keeps intimate wishes private unless he chooses to disclose them.';
const wadeHash=createHash('sha256').update(wadeSource).digest('hex');
const wadeItem=prepareProfileItems({items:[{id:'c1',kind:'relationship',topic:'family_decisions',target:'son',rule:'Wade tends to control his son on family matters.'}]}).items;
const wadeProfile=createProfile(wadeItem,{characterId:'wade',sourceHash:wadeHash,source:wadeSource,analysisId:'browser'});
const store={settings:{global:{enabled:true,autoJudge:true,showConfidence:true,pauseOnOoc:true}},chat:{preferences:{charmMemory:true,lorebookMemory:true}},history:[],characters:{enabled:true,characters:[{id:'hunter',name:'Hunter',source:'Hunter is a lawyer.',sourceVisibleToMain:true}],npcs:[{id:'wade',name:'Wade',source:wadeSource,sourceHash:wadeHash,sourceVisibleToMain:false,profile:wadeProfile}]}};
const wadeEntry={...store.characters.npcs[0],kind:'npc',npcRole:'mixed'};
store.characters.npcs[0]={...wadeEntry,recordBank:createRecordBank({entity_type:'npc',entity_name:'Wade',intimacy_reference:{text:'Wade keeps intimate wishes private unless he chooses to disclose them.',source_ids:['S001']},records:[{type:'relationship',target:'son',when:['family matters'],rule:'Wade tends to control his son on family matters.',modality:'tendency',basis:'explicit',source_ids:['S001'],knowledge_domain:'none',knowledge_state:'none'}]},wadeEntry,'browser-records')};
const requests=[];
let failCharacterWrite=false;
let failWorldWrite=false;
let gateScenario=null;
let worldChoice='no';
const host=`<!doctype html><html><meta charset="utf-8"><style>:root{--SmartThemeBodyColor:#eee;--SmartThemeBlurTintColor:#25252b;--SmartThemeBorderColor:#666;--SmartThemeQuoteColor:#9cbfff}body{margin:0;background:#202025;color:var(--SmartThemeBodyColor);font:16px Arial}button,input,select,textarea{box-sizing:border-box;font:inherit}button{cursor:pointer}select,input,textarea{color:inherit;background:var(--SmartThemeBlurTintColor)}.menu_button{border:1px solid var(--SmartThemeBorderColor);border-radius:5px;padding:7px}.text_pole{width:100%;border:1px solid #666;padding:6px}.checkbox_label{display:flex;align-items:center;gap:6px}.checkbox_label input{width:auto}</style><link rel="stylesheet" href="${prefix}style.css"><div id="extensions_settings"></div><div id="extensionsMenu"></div><div id="leftSendForm"><button id="extensionsMenuButton">wand</button></div><textarea id="send_textarea"></textarea><script>
const listeners=new Map(), prompts={},macros={};
window.mock={chat:[],prompts,macros,errors:[],worldBooks:{'Hunter Lore':{entries:{1:{uid:1,key:['door'],content:'The council meets tomorrow.'},2:{uid:2,key:['unrelated'],content:'Not relevant.'}}},'Hunter Extra':{entries:{3:{uid:3,constant:true,content:'Hunter owns the house.'}}}},async emit(name,...args){for(const fn of listeners.get(name)||[])await fn(...args)}};
window.ctx={characterId:1,characters:[null,{avatar:'Hunter.png',data:{description:'Sawyer Valentine is Hunter’s colleague.',personality:'Hunter speaks carefully under pressure.',extensions:{world:'Hunter Lore'}}}],chatId:'test-room',name1:'User',name2:'Hunter',chat:mock.chat,extensionPrompts:prompts,saveMetadata:async()=>{},macros:{register(name,value){macros[name]=value.handler},category:{MISC:'misc'}}};
window.SillyTavern={getContext:()=>ctx};window.jQuery=fn=>fn();
window.toastr=Object.fromEntries(['info','success','error','warning'].map(name=>[name,(message)=>{if(name==='error')mock.errors.push(message);let container=document.getElementById('toast-container');if(!container){container=document.createElement('div');container.id='toast-container';document.body.append(container)}const item={find(){return {text(){}}},toggleClass(){},remove(){},fadeOut(_ms,callback){callback?.call(item)}};return item}]));
window.eventSource={on(name,fn){if(!listeners.has(name))listeners.set(name,[]);listeners.get(name).push(fn)}};
</script><script type="module" src="${prefix}index.js"></script></html>`;
const server=http.createServer(async(req,res)=>{try{
    if(req.url==='/favicon.ico'){res.statusCode=204;res.end();return;}
    if(req.url==='/'){res.setHeader('Content-Type','text/html');res.end(host);return;}
    if(req.url==='/script.js'){res.setHeader('Content-Type','application/javascript');res.end(`export const eventSource=window.eventSource;export const event_types=new Proxy({},{get:(_,key)=>key});export const chat_metadata={};export function saveSettingsDebounced(){};export function setExtensionPrompt(key,value){window.mock.prompts[key]=value};export function getRequestHeaders(){return {}}`);return;}
    if(req.url==='/scripts/extensions.js'){res.setHeader('Content-Type','application/javascript');res.end('export const extension_settings={};');return;}
    if(req.url==='/scripts/world-info.js'){res.setHeader('Content-Type','application/javascript');res.end("export const world_info={charLore:[{name:'Hunter',extraBooks:['Hunter Extra']}]};export async function loadWorldInfo(name){return window.mock.worldBooks[name]||null}");return;}
    if(req.url==='/scripts/extensions/shared.js'){res.setHeader('Content-Type','application/javascript');res.end(`export class ConnectionManagerRequestService {static getSupportedProfiles(){return [{id:'test-profile',name:'테스트 연결',model:'mock-model'}]} static getProfile(){return this.getSupportedProfiles()[0]} static validateProfile(){} static async sendRequest(_id,messages){const prompt=messages?.[0]?.content||'';if(prompt.startsWith('You are a source-grounded character retrieval compiler.')) { const name=prompt.split('ENTITY_NAME: ')[1].split('\\n')[0]; return {content:JSON.stringify({entity_type:'npc',entity_name:name,records:[{type:'knowledge',target:'',when:['office procedure'],rule:name+' knows office procedures.',modality:'fact',basis:'explicit',source_ids:['S001'],knowledge_domain:'professional',knowledge_state:'knows'},{type:'relationship',target:'Hunter',when:['interests change'],rule:name+' may help or oppose Hunter when her own interests change.',modality:'conditional',basis:'explicit',source_ids:['S001'],knowledge_domain:'none',knowledge_state:'none'}]})}; } if(prompt.startsWith('Read the supplied world prompt as source data.'))return {content:JSON.stringify({short_description:'A quiet garden world with ordinary physical limits.'})};if(prompt.startsWith('You are compiling a roleplay world prompt'))return {content:JSON.stringify({format:'scene-reader-world',version:1,name:'Moonlit Garden',short_description:'A garden whose gate responds to moonlight.',fixed_rules:'The garden remains an ordinary place except for its moonlit gate.',franchise:false,calendar_topics:[],records:[{id:'W001',category:'mechanism',when:'When moonlight reaches the gate.',keywords:['moonlight','gate'],rule:'Moonlight opens the garden gate.',source_quote:'Moonlight opens the garden gate.'}]})};if(prompt.startsWith('Find named individual NPCs'))return {content:'\`\`\`json\\n'+JSON.stringify({npcs:[{name:'Sawyer Valentine',aliases:['Sawyer'],hint:'Hunter colleague'}]})+'\\n\`\`\`'};if(prompt.startsWith('Extract only the confirmed minimum identity'))return {content:JSON.stringify({core:'An established colleague of Hunter.'})};return {content:JSON.stringify({ok:true,anchors:[],new_items:[],affected:[],knowledge_updates:[],possible_followups:[]})}}}`);return;}
    if(req.url.startsWith('/api/plugins/scene-reader-jev/')){
        let raw='';for await(const part of req)raw+=part;const body=raw?JSON.parse(raw):{};requests.push({url:req.url,body});
        res.setHeader('Content-Type','application/json');let result={ok:true};
        if(req.url.endsWith('/bootstrap'))result={...store,ok:true,storageVersion:2,migrated:true,keyStatus:'저장됨 ····mock',backups:[]};
        else if(req.url.endsWith('/transaction')){store.chat=body.chat;store.history=body.history;}
        else if(req.url.endsWith('/settings')){if(failWorldWrite){failWorldWrite=false;res.statusCode=500;res.end(JSON.stringify({error:'Simulated world save failure'}));return;}store.settings=body.settings;}
        else if(req.url.endsWith('/characters')) { if(failCharacterWrite){failCharacterWrite=false;res.statusCode=500;res.end(JSON.stringify({error:'Simulated failed save'}));return;} store.characters=body.value; }
        else if(req.url.endsWith('/chat'))store.chat=body.value;
        else if(req.url.endsWith('/history'))store.history=body.value;
        else if(req.url.endsWith('/systemone'))result={answers:Object.fromEntries(Object.entries(body.questions||{}).map(([key,q])=>[key,{choice:key==='scene_level'&&gateScenario?gateScenario.level:key==='scene_phase'&&gateScenario?gateScenario.phase:key==='scene_evidence'&&gateScenario?Object.keys(q.criteria).find(value=>value!=='none')||'none':key.startsWith('scene_participant_')&&gateScenario?'yes':key.startsWith('world_record_')?worldChoice:key.startsWith('verification_')?'fulfilled':key.endsWith('_presence') && key.startsWith('character_')?'active':key.includes('_profile_slot_1')?Object.keys(q.criteria)[1]||'none':key.endsWith('_response_direction')?'act':({primary_focus:'direct',scene_state:'active',event_state:'none',npc_presence:'none',context_change_source:'none'}[key]||Object.keys(q.criteria)[0]),confidence:1}]))};
        res.end(JSON.stringify(result));return;
    }
    if(req.url.startsWith(prefix)){const file=path.resolve(root,decodeURIComponent(req.url.slice(prefix.length)));if(!file.startsWith(root+path.sep))throw Error('path');res.setHeader('Content-Type',file.endsWith('.css')?'text/css':'application/javascript');res.end(await readFile(file));return;}
    res.statusCode=404;res.end('not found');
}catch(error){res.statusCode=500;res.end(error.message);}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
const errors=[];
try{
    const context=await browser.newContext({permissions:['clipboard-read','clipboard-write']});
    const page=await context.newPage();page.on('pageerror',error=>{errors.push(error.message);console.error(error.message)});page.on('console',message=>{if(message.type()==='error')console.error(message.text())});
    await page.goto(`http://127.0.0.1:${server.address().port}/`);
    await page.locator('#scene-reader-quick-button').waitFor();
    assert.equal(await page.locator('#scene-reader-extension-settings').evaluate(e=>e.open),false);
    await page.locator('#scene-reader-extension-settings > summary').click();
    await page.locator('#sr-extension-icon').uncheck();
    await page.waitForFunction(()=>document.getElementById('scene-reader-quick-button').hidden);
    assert.equal(store.settings.global.showChatIcon,false);
    assert.equal(store.settings.global.enabled,true,'hiding icon does not disable the extension');
    await page.reload();
    await page.locator('#scene-reader-extension-settings').waitFor();
    assert.equal(await page.locator('#scene-reader-extension-settings').evaluate(e=>e.open),false);
    assert.equal(await page.locator('#scene-reader-quick-button').isVisible(),false);
    await page.locator('#scene-reader-extension-settings > summary').click();
    await page.locator('#sr-extension-enabled').uncheck();
    await page.waitForFunction(()=>!document.getElementById('sr-enabled').checked);
    assert.equal(store.settings.global.enabled,false);
    await page.locator('#sr-extension-open').click();
    await page.locator('#scene-reader-dialog[open]').waitFor();
    assert.equal(await page.locator('#sr-run').isDisabled(),true);
    await page.locator('#sr-settings-button').click();
    await page.locator('#sr-enabled').check();
    await page.waitForFunction(()=>document.getElementById('sr-extension-enabled').checked);
    assert.equal(store.settings.global.enabled,true);
    await page.locator('#sr-close').click();
    await page.locator('#sr-extension-icon').check();
    await page.waitForFunction(()=>!document.getElementById('scene-reader-quick-button').hidden);
    await page.locator('#scene-reader-quick-button').click();
    await page.locator('#scene-reader-dialog[open]').waitFor();
    await page.evaluate(()=>window.toastr.info('toast layer check'));
    await page.waitForFunction(()=>document.getElementById('toast-container')?.parentElement?.id==='scene-reader-dialog');
    for(const width of [320,390,768,1280]){
        await page.setViewportSize({width,height:850});
        for(const tab of ['flow','advanced','conflict','characters']){
            await page.locator(`[data-sr-tab="${tab}"]`).click();
            assert.equal(await page.locator('#scene-reader-dialog').evaluate(e=>e.scrollWidth>e.clientWidth+2),false,`${width}/${tab}: overflow`);
            if ([390,1280].includes(width) && ['flow','advanced'].includes(tab)) {
                await mkdir(path.join(root,'artifacts'),{recursive:true});
                await page.screenshot({path:path.join(root,'artifacts',`release-${width}-${tab}.png`)});
            }
            const bad=await page.locator(`#sr-tab-${tab} button:visible`).evaluateAll(buttons=>buttons.filter(e=>e.clientWidth<28).map(e=>e.textContent));assert.equal(bad.length,0,`${width}/${tab}: narrow buttons`);
        }
    }
    await page.setViewportSize({width:390,height:850});await page.locator('[data-sr-tab="characters"]').click();
    await page.locator('#sr-character-new').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-lore-status').textContent.includes('연결 로어북'));
    assert.equal(await page.locator('#sr-character-lore-options input').count(),2,'connected character lorebooks are available');
    await page.locator('#sr-character-editor-cancel').click();
    await page.locator('[data-record-kind="npc"]').click();
    await page.locator('[data-character-view-id="wade"]').click();
    await page.locator('#sr-character-analysis-result').getByText('Wade tends to control his son on family matters.').waitFor();
    await page.locator('#sr-character-record-close').click();
    await page.locator('#sr-npc-sheet-new').click();
    assert.equal(await page.locator('#sr-character-npc-role').inputValue(),'mixed');
    assert.equal(await page.locator('#sr-character-lore-options input:checked').count(),0,'NPC lorebooks start unselected');
    assert.match(await page.locator('#sr-character-npc-lore-note').textContent(),/NPC 한 명/);
    await page.locator('#sr-character-npc-template').click();
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/NPC 시트/);
    await page.locator('#sr-character-npc-role').selectOption('ally');
    await page.locator('#sr-character-copy-prompt').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('복사했습니다'));
    assert.doesNotMatch(await page.evaluate(()=>navigator.clipboard.readText()),/The council meets tomorrow/);
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/Completed NPC sheet supplied alongside/);
    await page.locator('.sr-character-lore-picker summary').click();
    await page.locator('#sr-character-lore-options input').first().check();
    await page.locator('#sr-character-copy-prompt').click();
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/The council meets tomorrow/,'selected NPC lorebook joins the instruction');
    assert.doesNotMatch(await page.evaluate(()=>navigator.clipboard.readText()),/Completed NPC sheet supplied alongside/);
    const rosaJson={entity_type:'npc',entity_name:'Rosa Valentine',records:[{type:'relationship',target:'Hunter',when:['interests change'],rule:'Rosa may help or oppose Hunter when her own interests change.',modality:'conditional',basis:'explicit',source_ids:['S001'],knowledge_domain:'none',knowledge_state:'none'}]};
    await page.locator('#sr-character-import-file').setInputFiles({name:'rosa.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(rosaJson))});
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('형식 검사 완료'));
    await page.locator('#sr-character-import').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-modal').hidden);
    assert.ok(store.characters.npcs.some(entry=>entry.name==='Rosa Valentine'&&entry.npcRole==='ally'));
    await page.locator('#sr-settings-button').click();assert.equal(await page.locator('#sr-memory-charm').isDisabled(),true);assert.equal(await page.locator('#sr-memory-lorebook').isDisabled(),true);assert.equal(await page.locator('#sr-memory-reserved').isHidden(),true);assert.equal(await page.locator('.sr-developer-lock > summary').textContent(),'개발자 모드');
    await page.locator('#sr-reasoner-profile').selectOption('test-profile');
    await page.locator('#sr-continuity-enabled').check();
    await page.locator('[data-sr-tab="flow"]').click();
    await page.waitForFunction(()=>document.getElementById('sr-continuity-results')?.textContent.includes('테스트 연결'));
    assert.match(await page.locator('#sr-continuity-results').textContent(),/선택한 연결 프로필.*테스트 연결/s,'the selected profile is shown before the first continuity run');
    await page.locator('#sr-settings-button').click();
    await page.locator('#sr-continuity-enabled').uncheck();
    await page.locator('[data-sr-tab="characters"]').click();
    const beforeCompilation=requests.filter(r=>r.url.endsWith('/systemone')).length;
    const rosa=store.characters.npcs.find(entry=>entry.name==='Rosa Valentine');
    assert.equal(rosa.selectedLore.length,2,'selected NPC lore is saved with the record');
    await page.locator('[data-character-view-id="'+rosa.id+'"]').click();
    await page.locator('#sr-character-analysis-result').getByText('Rosa may help or oppose Hunter when her own interests change.',{exact:true}).waitFor();
    assert.equal(requests.filter(r=>r.url.endsWith('/systemone')).length,beforeCompilation,'static import never calls Jev');
    assert.equal(await page.locator('.sr-tabs [data-sr-tab]').count(),4,'no additional tabs');
    for(const width of [320,390,768,1280]) {
        await page.setViewportSize({width,height:850});
        assert.equal(await page.locator('#scene-reader-dialog').evaluate(e=>e.scrollWidth>e.clientWidth+2),false,'retrieval UI overflow at '+width);
        if(width<=600) assert.equal(await page.locator('.sr-record-person').first().isVisible(),true,'mobile records remain visible');
    }
    await mkdir(path.join(root,'artifacts'),{recursive:true});
    await page.screenshot({path:path.join(root,'artifacts','retrieval-desktop.png')});
    await page.setViewportSize({width:390,height:850});
    await page.locator('#sr-character-analysis-result').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(root,'artifacts','retrieval-mobile.png')});
    assert.equal(await page.locator('#sr-npc-read-names').count(),0,'NPC name-reading button was removed');
    await page.locator('[data-sr-tab="flow"]').click();
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Open the door.'});await mock.emit('MESSAGE_SENT',0);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.ok(!requests.some(r=>r.body.state?.memory_reference?.entries?.length),'reserved memory must not reach Jev even with old enabled settings');
    assert.ok(!requests.some(r=>r.body.state?.memory_reference?.entries?.some(e=>e.sourceId==='Hunter Extra:3')),'reserved auxiliary lore stays off');
    assert.ok(!requests.some(r=>r.body.state?.memory_reference?.entries?.some(e=>e.sourceId==='Hunter Lore:2')),'irrelevant lore must not reach Jev');
    assert.ok(await page.evaluate(()=>mock.prompts['scene-reader-router']?.length>0),'prompt slot receives injection');
    await page.context().grantPermissions(['clipboard-read','clipboard-write']);
    await page.locator('#sr-copy-debug').click();
    const debugReport=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));
    assert.ok(debugReport.jevOriginalChoices.primary_focus,'debug copy retains Jev original choices');
    assert.ok(debugReport.decisions.primary_focus,'debug copy retains final coordination');
    assert.ok(!JSON.stringify(debugReport).includes('Open the door.'),'debug copy excludes raw chat');
    await page.locator('#sr-settings-button').click();await page.locator('#sr-tab-settings details').filter({hasText:'검사용 전체 판정 기록'}).first().locator('summary').click();await page.locator('#sr-debug-open').click();
    assert.match(await page.locator('#sr-debug-preview').inputValue(),/Open the door\./,'reviewable full debug includes original RP evidence');
    await page.locator('#sr-debug-copy').click();
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/rawJevAnswers/);
    await page.evaluate(async()=>{mock.chat.push({is_user:false,mes:'Hunter opens the door.'});await mock.emit('MESSAGE_RECEIVED',1);mock.chat.push({is_user:true,mes:'(oOc: Explain.)',extra:{ooc_chat:true,ooc_instruction:'fixed wrapper'}});await mock.emit('MESSAGE_SENT',2);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.equal(await page.evaluate(()=>mock.prompts['scene-reader-router']), '');
    await page.locator('#sr-settings-button').click();await page.locator('#sr-injection-mode').selectOption('macro');
    const beforeMacro=requests.filter(r=>r.url.endsWith('/systemone')).length;
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Open the door again.'});await mock.emit('MESSAGE_SENT',3);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.ok(!requests.filter(r=>r.url.endsWith('/systemone')).slice(beforeMacro).some(r=>r.body.state?.memory_reference?.entries?.length),'reserved memory stays off in macro mode');
    const beforeLoreEdit=requests.filter(r=>r.url.endsWith('/systemone')).length;
    await page.evaluate(async()=>{
        mock.worldBooks['Hunter Lore'].entries[1].content='The door now needs a brass key.';
        await mock.emit('WORLDINFO_UPDATED','Hunter Lore',mock.worldBooks['Hunter Lore']);
        await mock.emit('GENERATION_AFTER_COMMANDS','swipe',{},false);
    });
    const afterLoreEdit=requests.filter(r=>r.url.endsWith('/systemone')).slice(beforeLoreEdit);
    assert.ok(!afterLoreEdit.some(r=>r.body.state?.memory_reference?.entries?.length),'lore edit does not activate reserved memory');
    assert.ok(!(await page.evaluate(()=>Object.values(mock.prompts).join(' '))).includes('The door now needs a brass key.'),'raw lore is not reinjected');
    await page.locator('#sr-settings-button').click();assert.equal(await page.locator('#sr-memory-lorebook').isDisabled(),true);
    await page.waitForFunction(()=>document.getElementById('sr-memory-status').textContent.includes('준비 중'));
    const beforeCharm=requests.filter(r=>r.url.endsWith('/systemone')).length;
    await page.evaluate(async()=>{window.__charmBridge={getStoryContext:()=> {throw new Error('reserved bridge must not be called')}};mock.chat.push({is_user:true,mes:'Ask about the promise.'});await mock.emit('MESSAGE_SENT',4);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    const charmRequest=requests.filter(r=>r.url.endsWith('/systemone')).slice(beforeCharm).find(r=>r.body.state?.memory_reference);
    assert.ok(!charmRequest?.body.state.memory_reference.entries.some(e=>e.sourceKind==='charm'),'reserved Charm bridge stays off');
    assert.ok(!charmRequest?.body.state.memory_reference.entries.some(e=>e.sourceKind==='lorebook'),'disabled character lore is not sent');
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Wade enters the room.'});await mock.emit('MESSAGE_SENT',5);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.ok(requests.some(r=>r.body.state?.character_profiles?.people?.some(person=>person.name==='Wade' && person.profileCandidates.length)),'stored Wade rules reach live Jev selection');
    assert.match(await page.evaluate(()=>mock.macros['scene-reader']?.()||''),/Wade[^\n]*Wade tends to control his son on family matters\./,'the selected rule reaches the final injection');
    gateScenario={level:'3',phase:'active'};
    const beforePause=requests.length;
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Wade and Hunter begin an explicit sexual interaction.'});await mock.emit('MESSAGE_SENT',6);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    const pausedRequests=requests.slice(beforePause).filter(r=>r.url.endsWith('/systemone'));
    assert.equal(pausedRequests.length,1,'confirmed sexual scene uses only the small scene-state check');
    const pausedPrompt=await page.evaluate(()=>mock.macros['scene-reader']?.()||'');
    assert.match(pausedPrompt,/Wade keeps intimate wishes private/,'participating character reference remains available');
    assert.ok(!pausedPrompt.includes('CHARACTER_EXECUTION'),'dynamic character direction pauses');
    assert.match(pausedPrompt,/genre, setting, tone, prose style/,'fixed prompt coexistence remains');
    gateScenario={level:'0',phase:'ended'};
    const beforeResume=requests.length;
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'They finish and turn to a different conversation.'});await mock.emit('MESSAGE_SENT',7);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.ok(requests.slice(beforeResume).filter(r=>r.url.endsWith('/systemone')).length>1,'normal Jev judgment resumes after a confirmed end');
    gateScenario=null;
    await mkdir(path.join(root,'artifacts'),{recursive:true});await page.locator('[data-sr-tab="characters"]').click();await page.locator('#sr-character-analysis-result').scrollIntoViewIfNeeded();await page.screenshot({path:path.join(root,'artifacts','mobile-characters.png')});
    await page.evaluate(()=>{document.documentElement.style.setProperty('--SmartThemeBodyColor','#202020');document.documentElement.style.setProperty('--SmartThemeBlurTintColor','#f5f5f7');});await page.screenshot({path:path.join(root,'artifacts','mobile-light.png')});
    await page.locator('#sr-npc-sheet-new').click();
    assert.match(await page.locator('#sr-character-npc-lore-note').textContent(),/NPC 한 명/);
    await page.locator('#sr-character-editor-cancel').click();
    await page.locator('[data-sr-tab="flow"]').click();
    for (const id of ['sr-roleplay-pace','sr-event-chance','sr-progression-mode','sr-judgment-style','sr-world-export','sr-world-import-open','sr-world-import-panel']) assert.equal(await page.locator('#'+id).count(),0,`${id} removed`);
    for (const value of ['static','dynamic','balanced']) {
        await page.locator('#sr-development-style').selectOption(value);
        await page.waitForFunction(value=>document.getElementById('sr-development-style').value===value,value);
        await page.locator('[data-sr-tab="advanced"]').click();await page.locator('[data-sr-tab="flow"]').click();
        assert.equal(await page.locator('#sr-development-style').inputValue(),value);
        assert.equal(store.chat.preferences.developmentStyle,value);
    }
    for (const [id,key,value] of [['sr-relationship-pace','relationshipPace','slow'],['sr-resolution-pace','resolutionPace','fast'],['sr-appearance-chance','appearanceChance','35']]) {
        await page.locator('#'+id).selectOption(value);
        await page.locator('[data-sr-tab="advanced"]').click();await page.locator('[data-sr-tab="flow"]').click();
        assert.equal(String(store.chat.preferences[key]),value);
        assert.equal(await page.locator('#'+id).inputValue(),value);
    }
    await page.locator('[data-sr-tab="advanced"]').click();
    await page.locator('#sr-advanced-style').selectOption('active');
    await page.locator('[data-sr-tab="flow"]').click();await page.locator('[data-sr-tab="advanced"]').click();
    assert.equal(store.chat.preferences.advancedStyle,'active');
    assert.equal(await page.locator('#sr-advanced-style').inputValue(),'active');
    await page.locator('[data-sr-tab="advanced"]').click();await page.locator('#sr-world-new').evaluate(e=>e.closest('details').open=true);await page.locator('#sr-world-new').click();
    await page.locator('#sr-world-edit-name').fill('Garden world');await page.locator('#sr-world-edit-prompt').fill('An ordinary garden with no supernatural powers.');await page.locator('#sr-world-save').click();
    await page.locator('#sr-world-editor').waitFor({state:'hidden'});assert.ok(store.settings.worlds.some(w=>w.name==='Garden world'));
    await page.locator('#sr-world-manager-list button').filter({hasText:'Garden world'}).click();
    await page.locator('#sr-world-edit-prompt').fill('A quiet garden by the river.');await page.locator('#sr-world-save').click();
    await page.locator('#sr-world-editor').waitFor({state:'hidden'});
    assert.equal(store.settings.worlds.find(w=>w.name==='Garden world').prompt,'A quiet garden by the river.');
    await page.locator('#sr-world-manager-list button').filter({hasText:'Garden world'}).click();await page.locator('#sr-world-delete').click();await page.locator('#sr-world-editor').waitFor({state:'hidden'});
    assert.equal(store.settings.worlds.some(w=>w.name==='Garden world'),false);
    await page.locator('#sr-settings-button').click();
    assert.equal(await page.locator('#sr-progress-intensity').inputValue(),'1.0');
    await page.locator('#sr-progress-intensity-up').click();
    await page.waitForFunction(()=>document.getElementById('sr-progress-intensity').value==='1.1');
    await page.locator('[data-sr-tab="flow"]').click();await page.locator('#sr-settings-button').click();
    assert.equal(store.chat.preferences.progressIntensity,1.1);
    assert.equal(await page.locator('#sr-progress-intensity-value').textContent(),'1.1');
    await page.locator('#sr-progress-intensity-down').click();
    await page.waitForFunction(()=>document.getElementById('sr-progress-intensity').value==='1.0');
    await page.locator('#sr-progress-intensity-reset').click();
    assert.equal(store.chat.preferences.progressIntensity,1);
    await page.screenshot({path:path.join(root,'artifacts','mobile-settings.png')});
    await page.locator('#sr-copy-macro').evaluate(e=>{const d=e.closest('details');if(d)d.open=true;});await page.locator('#sr-copy-macro').click();
    assert.equal(await page.evaluate(()=>navigator.clipboard.readText()),'{{scene-reader}}');
    await page.locator('#sr-close').click();
    await page.waitForFunction(()=>document.getElementById('toast-container')?.parentElement===document.body);
    // Full public Character Reasoner workflow inside the existing character tab.
    await page.locator('#sr-extension-open').click();
    await page.locator('[data-sr-tab="characters"]').click();
    await page.locator('#sr-character-new').click();
    await page.locator('#sr-character-read-sheet').click();
    assert.equal(await page.locator('#sr-character-name').inputValue(),'Hunter');
    assert.match(await page.locator('#sr-character-source').inputValue(),/Sawyer Valentine/);
    assert.match(await page.locator('#sr-character-source').inputValue(),/Hunter speaks carefully under pressure/);
    await page.locator('#sr-character-copy-prompt').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('복사했습니다'));
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/ENTITY_NAME: Hunter/);
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/Hunter speaks carefully under pressure/,'character personality joins the copied analysis request');
    const external={entity_type:'character',entity_name:'Hunter',records:[{type:'knowledge',target:'self',when:['before confirmation'],rule:'Hunter suspects the invitation is a trap.',modality:'possibility',basis:'explicit',source_ids:['S001'],knowledge_domain:'event',knowledge_state:'suspects'}]};
    const beforeImport=requests.filter(r=>r.url.endsWith('/systemone')).length;
    await page.locator('#sr-character-import-file').setInputFiles({name:'hunter.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(external))});
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('형식 검사 완료'));
    await page.locator('#sr-character-import').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-modal').hidden);
    assert.equal(requests.filter(r=>r.url.endsWith('/systemone')).length,beforeImport,'import does not run Jev revalidation');
    await page.locator('[data-record-kind="character"]').click();
    const group1=store.characters.recordGroups.find(g=>g.name==='Hunter');
    const firstVersion=group1.versions[0].id;
    assert.equal(group1.versions.length,1);
    await page.locator('[data-record-version="'+firstVersion+'"][data-record-action="edit"]').click();
    external.records[0].rule='Hunter doubts the invitation is genuine.';
    await page.locator('#sr-character-import-file').setInputFiles({name:'hunter-updated.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(external))});
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('형식 검사 완료'));
    await page.locator('#sr-character-import').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-modal').hidden);
    assert.equal(store.characters.recordGroups.find(g=>g.name==='Hunter').versions.length,2,'editing one file creates a dated version');
    await page.locator('[data-record-version="'+firstVersion+'"][data-record-action="apply"]').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('선택한 버전을 적용'));
    await page.locator('[data-record-version="'+firstVersion+'"][data-record-action="view"]').click();
    assert.match(await page.locator('#sr-character-version-preview-text').textContent(),/suspects the invitation is a trap/);
    for(const width of [320,390,768,1280]) {
        await page.setViewportSize({width,height:850});
        assert.equal(await page.locator('#scene-reader-dialog').evaluate(e=>e.scrollWidth>e.clientWidth+2),false,'version UI overflow at '+width);
    }
    await page.screenshot({path:path.join(root,'artifacts','character-versions-desktop.png')});
    await page.setViewportSize({width:390,height:850});
    await page.locator('[data-record-version="'+firstVersion+'"][data-record-action="edit"]').click();
    await page.screenshot({path:path.join(root,'artifacts','character-import-mobile.png')});
    await page.locator('#sr-character-editor-cancel').click();
    await page.locator('[data-sr-tab="flow"]').click();
    await page.evaluate(()=>{mock.chat.push({is_user:true,name:'User',mes:'Hunter examines the invitation. Is it a trap?'});document.getElementById('send_textarea').value='';});
    await page.locator('#sr-run').click();
    await page.waitForFunction(()=>(mock.macros['scene-reader']?.() || '').includes('Hunter suspects the invitation is a trap.'));
    assert.ok(!Object.keys(requests.filter(r=>r.url.endsWith('/systemone')).at(-1).body.questions).some(key=>/response_direction|response_basis/.test(key)));
    await page.locator('#sr-close').click();
    await page.reload();
    await page.locator('#sr-extension-open').evaluate(e=>e.closest('details').open=true);
    await page.locator('#sr-extension-open').click();await page.locator('[data-sr-tab="characters"]').click();
    assert.equal(store.characters.characters.find(e=>e.name==='Hunter').appliedRecordVersion,firstVersion);
    page.once('dialog',dialog=>dialog.accept());
    await page.locator('[data-record-version="'+firstVersion+'"][data-record-action="delete"]').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('해당 버전을 삭제'));
    assert.equal(store.characters.recordGroups.find(g=>g.name==='Hunter').versions.length,1,'only the selected dated file is deleted');
    const remaining=store.characters.recordGroups.find(g=>g.name==='Hunter').versions[0].id;
    await page.locator('[data-record-version="'+remaining+'"][data-record-action="edit"]').click();
    await page.locator('#sr-character-import-file').setInputFiles({name:'hunter-failed.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(external))});
    const beforeFailedSave=JSON.stringify(store.characters);
    failCharacterWrite=true;
    await page.locator('#sr-character-import').click();
    await page.waitForFunction(()=>document.getElementById('sr-character-import-status').textContent.includes('저장되지 않음'));
    assert.equal(JSON.stringify(store.characters),beforeFailedSave,'failed persistence keeps stored versions');
    await page.locator('#sr-character-error-copy').click();
    const errorLog=JSON.parse(await page.evaluate(()=>navigator.clipboard.readText()));
    assert.equal(errorLog.stage,'save');
    assert.ok(!JSON.stringify(errorLog).includes('Hunter suspects the invitation is a trap.'),'character error report omits source content');
    await page.locator('#sr-character-editor-cancel').click();
    assert.equal(await page.locator('.sr-tabs [data-sr-tab]').count(),4);
    await page.locator('#sr-close').click();
    store.settings.global.ownerUnlocked=false;
    await page.reload();
    await page.locator('#sr-extension-open').evaluate(e=>e.closest('details').open=true);
    await page.locator('#sr-extension-open').click();
    await page.locator('[data-sr-tab="advanced"]').click();
    await page.locator('#sr-world-new').evaluate(e=>e.closest('details').open=true);
    assert.equal(await page.locator('#sr-world-advanced').evaluate(e=>e.hidden),false,'advanced world importer is available without developer unlock');
    assert.equal(await page.locator('#sr-owner-card').evaluate(e=>e.hidden),true,'other developer tools remain locked');
    await page.locator('#sr-world-advanced').evaluate(e=>e.open=true);
    await page.locator('#sr-world-advanced-copy').click();
    assert.match(await page.evaluate(()=>navigator.clipboard.readText()),/scene-reader-world/,'copy supplies the world compiler contract');
    await page.locator('#sr-world-advanced-source').fill('Moonlight opens the garden gate.');
    await page.locator('#sr-world-advanced-generate').click();
    await page.waitForFunction(()=>document.getElementById('sr-world-advanced-status').textContent.includes('생성 완료'));
    assert.match(await page.locator('#sr-world-advanced-json').inputValue(),/Moonlight opens the garden gate/);
    await page.locator('#sr-world-advanced-save').click();
    await page.waitForFunction(()=>document.getElementById('sr-world-manager-list').textContent.includes('Moonlit Garden'));
    const advancedWorld=store.settings.worlds.find(world=>world.name==='Moonlit Garden');
    assert.equal(advancedWorld.advanced.records.length,1,'advanced JSON survives settings persistence');
    await page.locator('#sr-world-manager-list button').filter({hasText:'Moonlit Garden'}).click();
    assert.match(await page.locator('#sr-world-advanced-json').inputValue(),/Moonlight opens the garden gate/,'saved advanced world can be reopened');
    const validWorldJson=await page.locator('#sr-world-advanced-json').inputValue();
    const beforeInvalid=JSON.stringify(store.settings.worlds);
    await page.locator('#sr-world-advanced-json').fill('{invalid');
    await page.locator('#sr-world-advanced-save').click();
    await page.waitForFunction(()=>document.getElementById('sr-world-advanced-status').textContent.includes('검증 실패'));
    assert.equal(JSON.stringify(store.settings.worlds),beforeInvalid,'malformed world import preserves prior data');
    await page.locator('#sr-world-advanced-file').setInputFiles({name:'world.json',mimeType:'application/json',buffer:Buffer.from(validWorldJson)});
    await page.waitForFunction(()=>document.getElementById('sr-world-advanced-status').textContent.includes('world.json'));
    assert.equal(await page.locator('#sr-world-advanced-json').inputValue(),validWorldJson);
    failWorldWrite=true;
    await page.locator('#sr-world-advanced-save').click();
    await page.waitForFunction(()=>document.getElementById('sr-world-advanced-status').textContent.includes('처리 실패'));
    assert.equal(JSON.stringify(store.settings.worlds),beforeInvalid,'failed server write preserves saved world bank');
    const locallySaved=await page.evaluate(()=>JSON.parse(localStorage.getItem('scene-reader-custom-worlds-v1')));
    assert.deepEqual(locallySaved,store.settings.worlds,'failed server write restores browser copy');
    assert.equal(await page.locator('#sr-world-advanced-json').inputValue(),validWorldJson,'failed save preserves editor input');
    await page.evaluate(()=>mock.errors=[]);
    for(const width of [320,390,768,1280]) {
        await page.setViewportSize({width,height:850});
        assert.equal(await page.locator('#scene-reader-dialog').evaluate(e=>e.scrollWidth>e.clientWidth+2),false,'advanced world UI overflow at '+width);
    }
    await page.locator('#sr-world-advanced').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(root,'artifacts','world-editor-desktop.png')});
    await page.locator('#sr-world-advanced-cancel').click();
    await page.reload();
    await page.locator('#sr-extension-open').evaluate(e=>e.closest('details').open=true);
    await page.locator('#sr-extension-open').click();
    await page.locator('[data-sr-tab="flow"]').click();
    await page.locator('#sr-world-profile').selectOption(advancedWorld.id);
    worldChoice='yes';
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'At the moonlit garden gate, Hunter waits.'});await mock.emit('MESSAGE_SENT',mock.chat.length-1);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    await page.waitForFunction(()=>(mock.macros['scene-reader-world']?.()||'').includes('Moonlight opens the garden gate.'));
    assert.match(await page.evaluate(()=>mock.macros['scene-reader-world']?.()||''),/ordinary place.*Moonlight opens the garden gate/s,'chosen world record reaches the world macro');
    const worldGate=requests.filter(request=>request.url.endsWith('/systemone')).findLast(request=>request.body.state?.world_record_candidates?.length);
    assert.equal(worldGate.body.state.world_record_candidates[0].id,'W001','the scene gate judges bounded world candidates');
    gateScenario={level:'3',phase:'active'};
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'At the moonlit garden gate, the explicit sexual interaction begins.'});await mock.emit('MESSAGE_SENT',mock.chat.length-1);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    await page.waitForFunction(()=>(mock.macros['scene-reader-world']?.()||'').includes('Moonlight opens the garden gate.'));
    assert.match(await page.evaluate(()=>mock.macros['scene-reader-world']?.()||''),/Moonlight opens the garden gate/,'relevant world records remain in the NSFW route');
    gateScenario={level:'0',phase:'ended'};
    worldChoice='no';
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'They leave the garden and discuss ordinary work.'});await mock.emit('MESSAGE_SENT',mock.chat.length-1);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    await page.waitForFunction(()=>(mock.macros['scene-reader-world']?.()||'').includes('ordinary place'));
    assert.doesNotMatch(await page.evaluate(()=>mock.macros['scene-reader-world']?.()||''),/Moonlight opens the garden gate/,'unrelated world rule is omitted');
    worldChoice='invalid';
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Hunter returns to the garden.'});await mock.emit('MESSAGE_SENT',mock.chat.length-1);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.equal(store.chat.lastJudgment.worldSelection.status,'fallback');
    assert.match(await page.evaluate(()=>mock.macros['scene-reader-world']?.()||''),/Scope: When moonlight reaches the gate\.\nMoonlight opens the garden gate/,'invalid selector response falls back with conditions intact');
    worldChoice='no';
    gateScenario=null;
    await page.locator('#sr-world-profile').selectOption('current');
    await page.locator('.sr-seasonal-options').evaluate(e=>e.open=true);
    await page.locator('#sr-season-holidays').check();
    await page.locator('#sr-season-college_football').check();
    await page.locator('#sr-season-us_university').check();
    await new Promise((resolve,reject)=>{const started=Date.now();const poll=()=>store.chat.preferences?.seasonalReferences?.length===3?resolve():Date.now()-started>3000?reject(new Error('Seasonal choices were not saved')):setTimeout(poll,20);poll();});
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Current date: 2026-10-30. The American campus prepares for the weekend.'});await mock.emit('MESSAGE_SENT',mock.chat.length-1);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    await page.waitForFunction(()=>(mock.macros['scene-reader-world']?.()||'').includes('Halloween week'));
    const seasonalPayload=await page.evaluate(()=>mock.macros['scene-reader-world']?.()||'');
    assert.match(seasonalPayload,/college-football/);
    assert.match(seasonalPayload,/autumn semester/);
    assert.equal(await page.locator('.sr-tabs [data-sr-tab]').count(),4,'world tools stay within the existing tabs');
    for(const width of [320,390,768,1280]) {
        await page.setViewportSize({width,height:850});
        assert.equal(await page.locator('#scene-reader-dialog').evaluate(e=>e.scrollWidth>e.clientWidth+2),false,'seasonal UI overflow at '+width);
    }
    await page.setViewportSize({width:390,height:850});
    await page.locator('.sr-seasonal-options').scrollIntoViewIfNeeded();
    await page.screenshot({path:path.join(root,'artifacts','world-seasonal-mobile.png')});
    await page.locator('#sr-settings-button').click();
    await page.locator('#sr-world-injection-mode').selectOption('depth');
    await page.evaluate(async()=>{mock.chat.push({is_user:true,mes:'Current date: 2026-10-31. They continue across campus.'});await mock.emit('MESSAGE_SENT',mock.chat.length-1);await mock.emit('GENERATION_AFTER_COMMANDS','normal',{},false);});
    assert.match(await page.evaluate(()=>JSON.stringify(mock.prompts)),/Halloween week/,'seasonal world reaches depth injection');
    assert.equal(await page.evaluate(()=>mock.macros['scene-reader-world']?.()||''),'','depth mode leaves no duplicate world macro');
    await page.locator('#sr-enabled').uncheck();
    await page.waitForFunction(()=>!JSON.stringify(mock.prompts).includes('Halloween week'));
    assert.equal(await page.evaluate(()=>mock.macros['scene-reader-world']?.()||''),'','disabled extension removes world macro');
    assert.deepEqual(errors,[]);assert.deepEqual(await page.evaluate(()=>mock.errors),[]);
    console.log('Browser passed: 4 viewport sizes × 4 tabs, character and world compile/save, seasonal context, live world selection, NSFW pause/resume injection, OOC, delete, clipboard.');
}finally{await browser.close();await new Promise(resolve=>server.close(resolve));}
